export const conversationData = {
  users: [
    {
      id: 1,
      image:
        "http://fgs.entrepreware.com/theme/image.php/academi/core/1634130003/u/f1",
      name: "Feras Osama Hassan",
      role: "Student",
      studentClass: "Language Primary 1",
      type: "user",
      chat: [
        {
          id: 1,
          text: "test",
          timesent: "04:54 PM",
          date: "Thursday, 12 November 2020",
          seen: false,
          senderid: 1,
          recieverid: 2,
        },
        {
          id: 2,
          text: "test",
          timesent: "04:54 PM",
          date: "Thursday, 12 November 2020",
          seen: false,
          senderid: 1,
          recieverid: 2,
        },
        {
          id: 3,
          text: "test",
          timesent: "04:54 PM",
          date: "Thursday, 12 November 2020",
          seen: false,
          senderid: 1,
          recieverid: 2,
        },
        {
          id: 4,
          text: "test",
          timesent: "04:54 PM",
          date: "Thursday, 12 November 2020",
          seen: false,
          senderid: 1,
          recieverid: 2,
        },
      ],
    },
    {
      id: 2,
      image:
        "http://fgs.entrepreware.com/theme/image.php/academi/core/1634130003/u/f1",
      name: "Feras Osama Hassan",
      role: "Student",
      studentClass: "Language Primary 1",
      type: "user",
      chat: [
        {
          id: 5,
          text: "test",
          timesent: "04:54 PM",
          date: "Thursday, 12 November 2020",
          seen: false,
          senderid: 1,
          recieverid: 2,
        },
        {
          id: 6,
          text: "test",
          timesent: "04:54 PM",
          date: "Thursday, 12 November 2020",
          seen: false,
          senderid: 1,
          recieverid: 2,
        },
        {
          id: 7,
          text: "test",
          timesent: "04:54 PM",
          date: "Thursday, 12 November 2020",
          seen: false,
          senderid: 1,
          recieverid: 2,
        },
        {
          id: 8,
          text: "test",
          timesent: "04:54 PM",
          date: "Thursday, 12 November 2020",
          seen: false,
          senderid: 1,
          recieverid: 2,
        },
      ],
    },
    {
      id: 3,
      image:
        "http://fgs.entrepreware.com/theme/image.php/academi/core/1634130003/u/f1",
      name: "Feras Osama Hassan",
      role: "Student",
      studentClass: "Language Primary 1",
      type: "user",
      chat: [],
    },
    {
      id: 4,
      image:
        "http://fgs.entrepreware.com/theme/image.php/academi/core/1634130003/u/f1",
      name: "Feras Osama Hassan",
      role: "Student",
      studentClass: "Language Primary 1",
      type: "user",
      chat: [],
    },
    {
      id: 5,
      image:
        "http://fgs.entrepreware.com/theme/image.php/academi/core/1634130003/u/f1",
      name: "Feras Osama Hassan",
      role: "Student",
      studentClass: "Language Primary 1",
      type: "user",
      chat: [],
    },
    {
      id: 6,
      image:
        "http://fgs.entrepreware.com/theme/image.php/academi/core/1634130003/u/f1",
      name: "Feras Osama Hassan",
      role: "Student",
      studentClass: "Language Primary 1",
      type: "user",
      chat: [],
    },
    {
      id: 7,
      image:
        "http://fgs.entrepreware.com/theme/image.php/academi/core/1634130003/u/f1",
      name: "Feras Osama Hassan",
      role: "Student",
      studentClass: "Language Primary 1",
      type: "user",
      chat: [],
    },
  ],
  messages: [
    {
      id: 1,
      image:
        "http://fgs.entrepreware.com/theme/image.php/academi/core/1634130003/u/f1",
      name: "Feras Osama Hassan",
      role: "Student",
      studentClass: "Language Primary 1",
      type: "message",
      chat: [
        {
          id: 1,
          text: "test",
          timesent: "04:54 PM",
          date: "Thursday, 12 November 2020",
          seen: false,
          senderid: 1,
          recieverid: 2,
        },
        {
          id: 2,
          text: "test",
          timesent: "04:54 PM",
          date: "Thursday, 12 November 2020",
          seen: false,
          senderid: 1,
          recieverid: 2,
        },
        {
          id: 3,
          text: "test",
          timesent: "04:54 PM",
          date: "Thursday, 12 November 2020",
          seen: false,
          senderid: 1,
          recieverid: 2,
        },
        {
          id: 4,
          text: "test",
          timesent: "04:54 PM",
          date: "Thursday, 12 November 2020",
          seen: false,
          senderid: 1,
          recieverid: 2,
        },
      ],
    },
    {
      id: 2,
      image:
        "http://fgs.entrepreware.com/theme/image.php/academi/core/1634130003/u/f1",
      name: "Feras Osama Hassan",
      role: "Student",
      studentClass: "Language Primary 1",
      type: "message",
      chat: [
        {
          id: 5,
          text: "test",
          timesent: "04:54 PM",
          date: "Thursday, 12 November 2020",
          seen: false,
          senderid: 1,
          recieverid: 2,
        },
        {
          id: 6,
          text: "test",
          timesent: "04:54 PM",
          date: "Thursday, 12 November 2020",
          seen: false,
          senderid: 1,
          recieverid: 2,
        },
        {
          id: 7,
          text: "test",
          timesent: "04:54 PM",
          date: "Thursday, 12 November 2020",
          seen: false,
          senderid: 1,
          recieverid: 2,
        },
        {
          id: 8,
          text: "test",
          timesent: "04:54 PM",
          date: "Thursday, 12 November 2020",
          seen: false,
          senderid: 1,
          recieverid: 2,
        },
      ],
    },
    {
      id: 3,
      image:
        "http://fgs.entrepreware.com/theme/image.php/academi/core/1634130003/u/f1",
      name: "Feras Osama Hassan",
      role: "Student",
      studentClass: "Language Primary 1",
      type: "message",
      chat: [
        {
          id: 1,
          text: "test",
          timesent: "04:54 PM",
          date: "Thursday, 12 November 2020",
          seen: false,
          senderid: 1,
          recieverid: 2,
        },
        {
          id: 2,
          text: "test",
          timesent: "04:54 PM",
          date: "Thursday, 12 November 2020",
          seen: false,
          senderid: 1,
          recieverid: 2,
        },
        {
          id: 3,
          text: "test",
          timesent: "04:54 PM",
          date: "Thursday, 12 November 2020",
          seen: false,
          senderid: 1,
          recieverid: 2,
        },
        {
          id: 4,
          text: "test",
          timesent: "04:54 PM",
          date: "Thursday, 12 November 2020",
          seen: false,
          senderid: 1,
          recieverid: 2,
        },
      ],
    },
    {
      id: 4,
      image:
        "http://fgs.entrepreware.com/theme/image.php/academi/core/1634130003/u/f1",
      name: "Feras Osama Hassan",
      role: "Student",
      studentClass: "Language Primary 1",
      type: "message",
      chat: [
        {
          id: 1,
          text: "test",
          timesent: "04:54 PM",
          date: "Thursday, 12 November 2020",
          seen: false,
          senderid: 1,
          recieverid: 2,
        },
        {
          id: 2,
          text: "test",
          timesent: "04:54 PM",
          date: "Thursday, 12 November 2020",
          seen: false,
          senderid: 1,
          recieverid: 2,
        },
        {
          id: 3,
          text: "test",
          timesent: "04:54 PM",
          date: "Thursday, 12 November 2020",
          seen: false,
          senderid: 1,
          recieverid: 2,
        },
        {
          id: 4,
          text: "test",
          timesent: "04:54 PM",
          date: "Thursday, 12 November 2020",
          seen: false,
          senderid: 1,
          recieverid: 2,
        },
      ],
    },
    {
      id: 5,
      image:
        "http://fgs.entrepreware.com/theme/image.php/academi/core/1634130003/u/f1",
      name: "Feras Osama Hassan",
      role: "Student",
      studentClass: "Language Primary 1",
      type: "message",
      chat: [
        {
          id: 1,
          text: "test",
          timesent: "04:54 PM",
          date: "Thursday, 12 November 2020",
          seen: false,
          senderid: 1,
          recieverid: 2,
        },
        {
          id: 2,
          text: "test",
          timesent: "04:54 PM",
          date: "Thursday, 12 November 2020",
          seen: false,
          senderid: 1,
          recieverid: 2,
        },
        {
          id: 3,
          text: "test",
          timesent: "04:54 PM",
          date: "Thursday, 12 November 2020",
          seen: false,
          senderid: 1,
          recieverid: 2,
        },
        {
          id: 4,
          text: "test",
          timesent: "04:54 PM",
          date: "Thursday, 12 November 2020",
          seen: false,
          senderid: 1,
          recieverid: 2,
        },
      ],
    },
    {
      id: 6,
      image:
        "http://fgs.entrepreware.com/theme/image.php/academi/core/1634130003/u/f1",
      name: "Feras Osama Hassan",
      role: "Student",
      studentClass: "Language Primary 1",
      type: "message",
      chat: [
        {
          id: 1,
          text: "test",
          timesent: "04:54 PM",
          date: "Thursday, 12 November 2020",
          seen: false,
          senderid: 1,
          recieverid: 2,
        },
        {
          id: 2,
          text: "test",
          timesent: "04:54 PM",
          date: "Thursday, 12 November 2020",
          seen: false,
          senderid: 1,
          recieverid: 2,
        },
        {
          id: 3,
          text: "test",
          timesent: "04:54 PM",
          date: "Thursday, 12 November 2020",
          seen: false,
          senderid: 1,
          recieverid: 2,
        },
        {
          id: 4,
          text: "test",
          timesent: "04:54 PM",
          date: "Thursday, 12 November 2020",
          seen: false,
          senderid: 1,
          recieverid: 2,
        },
      ],
    },
    {
      id: 7,
      image:
        "http://fgs.entrepreware.com/theme/image.php/academi/core/1634130003/u/f1",
      name: "Feras Osama Hassan",
      role: "Student",
      studentClass: "Language Primary 1",
      type: "message",
      chat: [
        {
          id: 1,
          text: "test",
          timesent: "04:54 PM",
          date: "Thursday, 12 November 2020",
          seen: false,
          senderid: 1,
          recieverid: 2,
        },
        {
          id: 2,
          text: "test",
          timesent: "04:54 PM",
          date: "Thursday, 12 November 2020",
          seen: false,
          senderid: 1,
          recieverid: 2,
        },
        {
          id: 3,
          text: "test",
          timesent: "04:54 PM",
          date: "Thursday, 12 November 2020",
          seen: false,
          senderid: 1,
          recieverid: 2,
        },
        {
          id: 4,
          text: "test",
          timesent: "04:54 PM",
          date: "Thursday, 12 November 2020",
          seen: false,
          senderid: 1,
          recieverid: 2,
        },
      ],
    },
  ],
};
